"use client";
import {useEffect,useRef,useState} from "react";
type P={x:number;y:number}; type Food=P&{r:number;taken:boolean}; type Target=P&{food?:Food;nest?:boolean}; type Ant=P&{id:number;a:number;speed:number;carry:Food|null;target:Target|null;manual:boolean;turn:number;clock:number}; type Trail=P&{power:number};
const W=1600,H=950,TAU=Math.PI*2,N={x:790,y:490,r:30}; const d2=(a:P,b:P)=>(a.x-b.x)**2+(a.y-b.y)**2; const clamp=(v:number,a:number,b:number)=>Math.max(a,Math.min(b,v));
function makeWorld(){let seed=817233;const rnd=()=> (seed=(seed*1664525+1013904223)>>>0)/4294967296;const food:Food[]=[];for(const [x,y,n,s] of [[280,235,24,65],[1280,235,20,58],[1325,720,26,70],[310,755,18,55]])for(let i=0;i<n;i++){const a=rnd()*TAU,r=Math.sqrt(rnd())*s;food.push({x:x+Math.cos(a)*r,y:y+Math.sin(a)*r,r:5+rnd()*2,taken:false})}const ants:Ant[]=Array.from({length:30},(_,i)=>{const a=rnd()*TAU,r=38+rnd()*48;return{id:i+1,x:N.x+Math.cos(a)*r,y:N.y+Math.sin(a)*r,a,speed:42+rnd()*13,carry:null,target:null,manual:false,turn:(rnd()-.5)*.6,clock:0}});return{food,ants,trails:[] as Trail[],stored:0}}
export default function Simulation(){const ref=useRef<HTMLCanvasElement>(null),selected=useRef<Ant|null>(null);const [stats,setStats]=useState({stored:0,field:88}),[toast,setToast]=useState("");
useEffect(()=>{const c=ref.current!,ctx=c.getContext("2d")!,w=makeWorld(),view={s:1,x:0,y:0};let raf=0,last=performance.now(),timer=0;const note=(s:string)=>{setToast(s);clearTimeout(timer);timer=window.setTimeout(()=>setToast(""),1500)};const sync=()=>setStats({stored:w.stored,field:w.food.filter(f=>!f.taken).length});
const resize=()=>{const p=Math.min(devicePixelRatio||1,2);c.width=innerWidth*p;c.height=innerHeight*p;view.s=Math.min(c.width/W,c.height/H);view.x=(c.width-W*view.s)/2;view.y=(c.height-H*view.s)/2};const point=(e:MouseEvent)=>({x:(e.clientX*c.width/innerWidth-view.x)/view.s,y:(e.clientY*c.height/innerHeight-view.y)/view.s});
const near=(a:P,r:number)=>{let hit:Food|null=null,b=r*r;for(const f of w.food)if(!f.taken&&d2(a,f)<b){b=d2(a,f);hit=f}return hit};const pickup=(a:Ant,f:Food|null)=>{if(!f||f.taken||a.carry)return;f.taken=true;a.carry=f;a.target=null;a.manual=false;sync()};const drop=(a:Ant)=>{if(!a.carry)return;a.carry=null;a.manual=false;a.target=null;w.stored++;sync();if(a===selected.current)note("PELLET ADDED TO COLONY STORES")};
const update=(a:Ant,dt:number)=>{let desired=a.a;if(a.manual&&a.target){const target=a.target;desired=Math.atan2(target.y-a.y,target.x-a.x);if(d2(a,target)<100){if(target.food)pickup(a,target.food);else if(target.nest)drop(a);a.target=null;a.manual=false}}else if(a.carry){desired=Math.atan2(N.y-a.y,N.x-a.x);a.clock-=dt;if(a.clock<=0){w.trails.push({x:a.x,y:a.y,power:1});a.clock=.2}if(d2(a,N)<N.r*N.r)drop(a)}else{const f=near(a,72);if(f)desired=Math.atan2(f.y-a.y,f.x-a.x);else{let best:Trail|null=null,score=0;for(const t of w.trails){const dd=d2(a,t),q=t.power/(35+Math.sqrt(dd));if(dd<10000&&q>score){score=q;best=t}}if(best)desired=Math.atan2(best.y-a.y,best.x-a.x);else desired+=a.turn*dt+(Math.random()-.5)*.22}pickup(a,near(a,9))}const diff=Math.atan2(Math.sin(desired-a.a),Math.cos(desired-a.a));a.a+=clamp(diff,-2.7*dt,2.7*dt);a.x+=Math.cos(a.a)*a.speed*dt;a.y+=Math.sin(a.a)*a.speed*dt;if(a.x<18||a.x>W-18){a.a=Math.PI-a.a;a.x=clamp(a.x,18,W-18)}if(a.y<18||a.y>H-18){a.a=-a.a;a.y=clamp(a.y,18,H-18)}};
const ground=()=>{ctx.fillStyle="#6f4b2e";ctx.fillRect(0,0,W,H);let s=22917,rnd=()=> (s=(s*1664525+1013904223)>>>0)/4294967296;for(let i=0;i<800;i++){ctx.globalAlpha=.14;ctx.fillStyle=rnd()>.5?"#26180f":"#d0a06d";ctx.fillRect(rnd()*W,rnd()*H,rnd()*2+1,rnd()*2+1)}ctx.globalAlpha=1;const g=ctx.createRadialGradient(N.x,N.y,3,N.x,N.y,70);g.addColorStop(0,"#060504");g.addColorStop(.42,"#17100a");g.addColorStop(.5,"#8c633d");g.addColorStop(1,"#5a371f00");ctx.fillStyle=g;ctx.beginPath();ctx.arc(N.x,N.y,70,0,TAU);ctx.fill();ctx.strokeStyle="#e7be7199";ctx.setLineDash([3,6]);ctx.beginPath();ctx.arc(N.x,N.y,44,0,TAU);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle="#efd091";ctx.font="bold 10px monospace";ctx.textAlign="center";ctx.fillText("NEST ENTRANCE",N.x,N.y+69)};
const ant=(a:Ant)=>{ctx.save();ctx.translate(a.x,a.y);ctx.rotate(a.a);if(a===selected.current){ctx.strokeStyle="#ffe74d99";ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,0,15,0,TAU);ctx.stroke()}ctx.fillStyle=a===selected.current?"#ffe23d":"#15120f";ctx.strokeStyle="#050403";for(const y of [-4,4])for(const x of [-2,4]){ctx.beginPath();ctx.moveTo(x,y/2);ctx.lineTo(x+5,y*1.7);ctx.stroke()}ctx.beginPath();ctx.ellipse(-5,0,5,3.5,0,0,TAU);ctx.ellipse(1,0,4,3,0,0,TAU);ctx.ellipse(6,0,3.5,3,0,0,TAU);ctx.fill();if(a.carry){ctx.fillStyle="#d6a43f";ctx.beginPath();ctx.arc(12,0,5,0,TAU);ctx.fill()}ctx.restore()};
const draw=()=>{const p=c.width/innerWidth;ctx.setTransform(p,0,0,p,0,0);ctx.fillStyle="#21150d";ctx.fillRect(0,0,innerWidth,innerHeight);ctx.setTransform(view.s,0,0,view.s,view.x,view.y);ground();for(const t of w.trails){ctx.globalAlpha=t.power*.25;ctx.fillStyle="#efb64d";ctx.beginPath();ctx.arc(t.x,t.y,2.5,0,TAU);ctx.fill()}ctx.globalAlpha=1;for(const f of w.food)if(!f.taken){ctx.fillStyle="#d7a43e";ctx.strokeStyle="#6e4316";ctx.beginPath();ctx.arc(f.x,f.y,f.r,0,TAU);ctx.fill();ctx.stroke()}const a=selected.current,target=a?.target;if(a&&target){ctx.strokeStyle="#ffe54dcc";ctx.setLineDash([5,6]);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(target.x,target.y);ctx.stroke();ctx.setLineDash([])}w.ants.forEach(ant)};
const tick=(now:number)=>{const dt=Math.min((now-last)/1000,.04);last=now;w.ants.forEach(a=>update(a,dt));for(let i=w.trails.length-1;i>=0;i--){w.trails[i].power-=dt*.055;if(w.trails[i].power<=0)w.trails.splice(i,1)}draw();raf=requestAnimationFrame(tick)};
const click=(e:MouseEvent)=>{const p=point(e);let hit:Ant|null=null,b=18**2;for(const a of w.ants)if(d2(p,a)<b){b=d2(p,a);hit=a}if(hit){selected.current=hit;hit.target=null;hit.manual=true;note(`WORKER ${String(hit.id).padStart(2,"0")} SELECTED`);return}const a=selected.current;if(!a)return;a.target=d2(p,N)<55**2&&a.carry?{...N,nest:true}:{x:clamp(p.x,15,W-15),y:clamp(p.y,15,H-15)};a.manual=true};const dbl=(e:MouseEvent)=>{const a=selected.current;if(!a){note("SELECT AN ANT FIRST");return}const f=near(point(e),18);if(f){a.target={x:f.x,y:f.y,food:f};a.manual=true;note("FOOD PICKUP ROUTE SET")}};
resize();addEventListener("resize",resize);c.addEventListener("click",click);c.addEventListener("dblclick",dbl);raf=requestAnimationFrame(tick);return()=>{cancelAnimationFrame(raf);clearTimeout(timer);removeEventListener("resize",resize);c.removeEventListener("click",click);c.removeEventListener("dblclick",dbl)}},[]);
return <section style={{position:"relative",width:"100%",height:"100%"}}><canvas ref={ref}/><div className="hud brand"><em>ANT // 01</em><h1>BLACKWOOD<br/>COLONY</h1><p>FORAGING OBSERVATION</p></div><div className="hud stats"><Stat title="COLONY STORES" value={stats.stored}/><Stat title="WORKERS" value={30}/><Stat title="FIELD FOOD" value={stats.field}/></div><div className="hud mode"><b>● FORAGE MODE</b><small> PHEROMONE NETWORK ACTIVE</small></div><div className="hud help"><b>CLICK ANT</b> SELECT &amp; CONTROL<br/><b>CLICK GROUND</b> MOVE SELECTED ANT<br/><b>DOUBLE-CLICK FOOD</b> PICK UP<br/><b>CLICK NEST</b> DELIVER FOOD</div>{toast&&<div className="hud toast">{toast}</div>}</section>}
function Stat({title,value}:{title:string;value:number}){return <div className="stat"><span>{title}</span><strong>{String(value).padStart(3,"0")}</strong><small> PELLETS</small></div>}
